### ISSUE TITLE
#support #UploadType

### ISSUE THREAD

**Issue by nietzscheson** [0soft/graphene-django-plus#17]
Hey, guys... I need your help.

How I can test a mutations with UploadType.

Our model Post

```python

class Post(Resource):
    image = models.ImageField(upload_to="post")
```
And my Test
```python
class PostTestCase(JSONWebTokenTestCase):
    
    def setUp(self):
        self.post = PostFactory

    def test_create(self):

        post = self.post.build()

        query = '''
            mutation($input: PostCreateInput!) {
                postCreate(input: $input) {
                    post{
                        id
                        image
                    }
                }
            }
        '''

        response = self.client.post(
            '/graphql',
            data={
                'operations': json.dumps({
                    'query': query,
                    'variables': {
                        'input': {
                            'image': None
                        },
                    },
                }),
                't_file': post.image,
                'map': json.dumps({
                    't_file': ['variables.input.image'],
                }),
            }
        )

        print(response)
```
And the response

```python
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
<WSGIRequest: POST '/graphql'>
.
----------------------------------------------------------------------
Ran 1 test in 0.087s

OK
Destroying test database for alias 'default'...
```
The file doesn't upload!

**Comment by bellini666** [comment]
Hi @nietzscheson 

I'm failing to understand why the file didn't upload from you example.

Either way, I haven't write any tests with file upload yet (something that would be nice to add to this repo =P). But we use that exactly feature with https://github.com/jaydenseric/apollo-upload-client on our projects here. You can probably check how that lib does the upload so you can mimic it, and also make sure that the graphene test client does allow for you to attach a file upload to it.

**Comment by nietzscheson** [comment]
Hey, @bellini666... In the project's configuration are we need something more? I don't know... this package: https://pypi.org/project/graphene-file-upload/ or this graphene view: https://github.com/lmcgartland/graphene-file-upload/blob/master/graphene_file_upload/django/__init__.py

**Comment by bellini666** [comment]
@nietzscheson graphene-django-plus already provides something very similar to that package. When using the `UploadType` you need to use its custom [GraphQLView](https://github.com/0soft/graphene-django-plus/blob/master/graphene_django_plus/views.py#L53) which extends the graphene's base one and adds support for the UploadType itself.

**Comment by nietzscheson** [comment]
Thanks, @bellini666 this works!
