### ISSUE TITLE
'FloatField' object has no attribute 'max_digits'

### ISSUE THREAD

**Issue by nietzscheson** [0soft/graphene-django-plus#27]
The last pipeline of my project worked correctly. This was two weeks ago. This week there have been several problems with this library. Now it is throwing me this error: `'FloatField' object has no attribute 'max_digits'`

For Django [Float and Decimal](https://docs.djangoproject.com/en/3.2/ref/models/fields/#floatfield-vs-decimalfield) are different: https://github.com/0soft/graphene-django-plus/blob/master/graphene_django_plus/schema.py#L116-L117

**Comment by bellini666** [comment]
Hey @nietzscheson , thanks for pointing those issues out.

For curiosity, what are you using these types schema things for? Since that functionality is still experimental and not yet documented here, I was curious on how did you discover it and what are you using for =P

**Comment by nietzscheson** [comment]
I do not know what happened. I was using v.2.3.2 and it started throwing these errors ... So I updated to the latest version. Very rare...
