### ISSUE TITLE
Use without relay?

### ISSUE THREAD

**Issue by nietzscheson** [0soft/graphene-django-plus#29]
Can I use this package without relay interface?

**Comment by bellini666** [comment]
Hey @nietzscheson .

This package right now is unfortunately very tied to relay (at least the mutations part is). There's an open issue here (https://github.com/0soft/graphene-django-plus/issues/1) regarding making relay optional, but I don't have the time to do that right now.

But feel free to try to make that happen and open a PR for the project, I'll gladly review it and integrate it if it looks good!

ps. I'm closing this issue as duplicate of that issue that I mentioned above

**Comment by nietzscheson** [comment]
I'm trying!
