### ISSUE TITLE
Project status - deprecated?

### ISSUE THREAD

**Issue by gdvalderrama** [0soft/graphene-django-plus#42]
Looking at [the releases](https://github.com/0soft/graphene-django-plus/releases) the latest release was 2 weeks ago.

However [this pinned issue](https://github.com/0soft/graphene-django-plus/issues/33) explicitly states that it's deprecated.

So, which is it?

AFAIK one of the dependencies used, [graphene-django-optimizer](https://github.com/tfoxy/graphene-django-optimizer), is deprecated (last update 2+ years ago) and is [not compatible with Django 4](https://github.com/tfoxy/graphene-django-optimizer/issues/91).

**Comment by bellini666** [comment]
Hi @gdvalderrama ,

I can understand the confusion =P

This lib is indeed deprecated. I'm currently focusing all my efforts on https://strawberry.rocks, which IMO is the best graphql solution for python atm, being very well maintained with a large community around it. I'm actually one of its code devs currently.

Regarding the update, it was a one time mostly to be able to upgrade my only project which I did not yet migrate to strawberry to django 4. Indeed graphene-django-optimizer doesn't work with it, but I forked it and made it work. You can use my fork if you want: https://github.com/bellini666/graphene-django-optimizer (install directly from git)

**Comment by gdvalderrama** [comment]
> Hi @gdvalderrama ,
> 
> I can understand the confusion =P
> 
> This lib is indeed deprecated. I'm currently focusing all my efforts on https://strawberry.rocks, which IMO is the best graphql solution for python atm, being very well maintained with a large community around it. I'm actually one of its code devs currently.
> 
> Regarding the update, it was a one time mostly to be able to upgrade my only project which I did not yet migrate to strawberry to django 4. Indeed graphene-django-optimizer doesn't work with it, but I forked it and made it work. You can use my fork if you want: https://github.com/bellini666/graphene-django-optimizer (install directly from git)

Amazing, thanks for clearing that up!
We've already mid-way through removing graphene django optimizer, but thanks for pointing at your fork 🙏🏻
